data_ingestion:

  source: "1M youtube_comments_cleaned.csv"
  output_dir: "data/raw"
  random_state: 42


data_preprocessing:

  input_path: "data/raw/cleaned_data.parquet"
  output_dir: "data/processed"
  test_size: 0.10
  val_size: 0.10
  random_state: 42

feature_engineering:

  train_path: "data/processed/train.parquet"

  val_path: "data/processed/val.parquet"

  test_path: "data/processed/test.parquet"

  model_name: "cardiffnlp/twitter-roberta-base-sentiment-latest"

  output_dir: "artifacts/features"